// All ISO 3166-1 countries, name + flag emoji. Flag emojis render with the
// system font on every modern OS (macOS, iOS, Android, Win 11 with the
// emoji font installed); Win 10 falls back to "GB", "US", etc. text, which
// is still readable. The list is sorted alphabetically by display name so
// the dropdown is browsable without a search box for now.
//
// Stored value is the country's English display name (the same string that
// already lives in DB columns today). The flag is rendered for the dropdown
// label and the selected display but not persisted, so existing rows with
// free-text country strings continue to render.

export interface Country {
  /** ISO 3166-1 alpha-2 code — lower-cased ASCII letters. */
  code: string
  /** English display name. This is what gets stored. */
  name: string
  /** Flag emoji (two regional-indicator code points). */
  flag: string
}

function flagFor(code: string): string {
  const upper = code.toUpperCase()
  const offset = 0x1f1e6 - 'A'.charCodeAt(0)
  return (
    String.fromCodePoint(upper.charCodeAt(0) + offset) +
    String.fromCodePoint(upper.charCodeAt(1) + offset)
  )
}

const NAMES: ReadonlyArray<[string, string]> = [
  ['af', 'Afghanistan'],
  ['ax', 'Åland Islands'],
  ['al', 'Albania'],
  ['dz', 'Algeria'],
  ['as', 'American Samoa'],
  ['ad', 'Andorra'],
  ['ao', 'Angola'],
  ['ai', 'Anguilla'],
  ['aq', 'Antarctica'],
  ['ag', 'Antigua and Barbuda'],
  ['ar', 'Argentina'],
  ['am', 'Armenia'],
  ['aw', 'Aruba'],
  ['au', 'Australia'],
  ['at', 'Austria'],
  ['az', 'Azerbaijan'],
  ['bs', 'Bahamas'],
  ['bh', 'Bahrain'],
  ['bd', 'Bangladesh'],
  ['bb', 'Barbados'],
  ['by', 'Belarus'],
  ['be', 'Belgium'],
  ['bz', 'Belize'],
  ['bj', 'Benin'],
  ['bm', 'Bermuda'],
  ['bt', 'Bhutan'],
  ['bo', 'Bolivia'],
  ['ba', 'Bosnia and Herzegovina'],
  ['bw', 'Botswana'],
  ['bv', 'Bouvet Island'],
  ['br', 'Brazil'],
  ['io', 'British Indian Ocean Territory'],
  ['vg', 'British Virgin Islands'],
  ['bn', 'Brunei'],
  ['bg', 'Bulgaria'],
  ['bf', 'Burkina Faso'],
  ['bi', 'Burundi'],
  ['kh', 'Cambodia'],
  ['cm', 'Cameroon'],
  ['ca', 'Canada'],
  ['cv', 'Cape Verde'],
  ['bq', 'Caribbean Netherlands'],
  ['ky', 'Cayman Islands'],
  ['cf', 'Central African Republic'],
  ['td', 'Chad'],
  ['cl', 'Chile'],
  ['cn', 'China'],
  ['cx', 'Christmas Island'],
  ['cc', 'Cocos (Keeling) Islands'],
  ['co', 'Colombia'],
  ['km', 'Comoros'],
  ['cg', 'Congo - Brazzaville'],
  ['cd', 'Congo - Kinshasa'],
  ['ck', 'Cook Islands'],
  ['cr', 'Costa Rica'],
  ['ci', 'Côte d’Ivoire'],
  ['hr', 'Croatia'],
  ['cu', 'Cuba'],
  ['cw', 'Curaçao'],
  ['cy', 'Cyprus'],
  ['cz', 'Czechia'],
  ['dk', 'Denmark'],
  ['dj', 'Djibouti'],
  ['dm', 'Dominica'],
  ['do', 'Dominican Republic'],
  ['ec', 'Ecuador'],
  ['eg', 'Egypt'],
  ['sv', 'El Salvador'],
  ['gq', 'Equatorial Guinea'],
  ['er', 'Eritrea'],
  ['ee', 'Estonia'],
  ['sz', 'Eswatini'],
  ['et', 'Ethiopia'],
  ['fk', 'Falkland Islands'],
  ['fo', 'Faroe Islands'],
  ['fj', 'Fiji'],
  ['fi', 'Finland'],
  ['fr', 'France'],
  ['gf', 'French Guiana'],
  ['pf', 'French Polynesia'],
  ['tf', 'French Southern Territories'],
  ['ga', 'Gabon'],
  ['gm', 'Gambia'],
  ['ge', 'Georgia'],
  ['de', 'Germany'],
  ['gh', 'Ghana'],
  ['gi', 'Gibraltar'],
  ['gr', 'Greece'],
  ['gl', 'Greenland'],
  ['gd', 'Grenada'],
  ['gp', 'Guadeloupe'],
  ['gu', 'Guam'],
  ['gt', 'Guatemala'],
  ['gg', 'Guernsey'],
  ['gn', 'Guinea'],
  ['gw', 'Guinea-Bissau'],
  ['gy', 'Guyana'],
  ['ht', 'Haiti'],
  ['hm', 'Heard & McDonald Islands'],
  ['hn', 'Honduras'],
  ['hk', 'Hong Kong SAR China'],
  ['hu', 'Hungary'],
  ['is', 'Iceland'],
  ['in', 'India'],
  ['id', 'Indonesia'],
  ['ir', 'Iran'],
  ['iq', 'Iraq'],
  ['ie', 'Ireland'],
  ['im', 'Isle of Man'],
  ['il', 'Israel'],
  ['it', 'Italy'],
  ['jm', 'Jamaica'],
  ['jp', 'Japan'],
  ['je', 'Jersey'],
  ['jo', 'Jordan'],
  ['kz', 'Kazakhstan'],
  ['ke', 'Kenya'],
  ['ki', 'Kiribati'],
  ['xk', 'Kosovo'],
  ['kw', 'Kuwait'],
  ['kg', 'Kyrgyzstan'],
  ['la', 'Laos'],
  ['lv', 'Latvia'],
  ['lb', 'Lebanon'],
  ['ls', 'Lesotho'],
  ['lr', 'Liberia'],
  ['ly', 'Libya'],
  ['li', 'Liechtenstein'],
  ['lt', 'Lithuania'],
  ['lu', 'Luxembourg'],
  ['mo', 'Macao SAR China'],
  ['mg', 'Madagascar'],
  ['mw', 'Malawi'],
  ['my', 'Malaysia'],
  ['mv', 'Maldives'],
  ['ml', 'Mali'],
  ['mt', 'Malta'],
  ['mh', 'Marshall Islands'],
  ['mq', 'Martinique'],
  ['mr', 'Mauritania'],
  ['mu', 'Mauritius'],
  ['yt', 'Mayotte'],
  ['mx', 'Mexico'],
  ['fm', 'Micronesia'],
  ['md', 'Moldova'],
  ['mc', 'Monaco'],
  ['mn', 'Mongolia'],
  ['me', 'Montenegro'],
  ['ms', 'Montserrat'],
  ['ma', 'Morocco'],
  ['mz', 'Mozambique'],
  ['mm', 'Myanmar (Burma)'],
  ['na', 'Namibia'],
  ['nr', 'Nauru'],
  ['np', 'Nepal'],
  ['nl', 'Netherlands'],
  ['nc', 'New Caledonia'],
  ['nz', 'New Zealand'],
  ['ni', 'Nicaragua'],
  ['ne', 'Niger'],
  ['ng', 'Nigeria'],
  ['nu', 'Niue'],
  ['nf', 'Norfolk Island'],
  ['kp', 'North Korea'],
  ['mk', 'North Macedonia'],
  ['mp', 'Northern Mariana Islands'],
  ['no', 'Norway'],
  ['om', 'Oman'],
  ['pk', 'Pakistan'],
  ['pw', 'Palau'],
  ['ps', 'Palestinian Territories'],
  ['pa', 'Panama'],
  ['pg', 'Papua New Guinea'],
  ['py', 'Paraguay'],
  ['pe', 'Peru'],
  ['ph', 'Philippines'],
  ['pn', 'Pitcairn Islands'],
  ['pl', 'Poland'],
  ['pt', 'Portugal'],
  ['pr', 'Puerto Rico'],
  ['qa', 'Qatar'],
  ['re', 'Réunion'],
  ['ro', 'Romania'],
  ['ru', 'Russia'],
  ['rw', 'Rwanda'],
  ['ws', 'Samoa'],
  ['sm', 'San Marino'],
  ['st', 'São Tomé and Príncipe'],
  ['sa', 'Saudi Arabia'],
  ['sn', 'Senegal'],
  ['rs', 'Serbia'],
  ['sc', 'Seychelles'],
  ['sl', 'Sierra Leone'],
  ['sg', 'Singapore'],
  ['sx', 'Sint Maarten'],
  ['sk', 'Slovakia'],
  ['si', 'Slovenia'],
  ['sb', 'Solomon Islands'],
  ['so', 'Somalia'],
  ['za', 'South Africa'],
  ['gs', 'South Georgia & South Sandwich Islands'],
  ['kr', 'South Korea'],
  ['ss', 'South Sudan'],
  ['es', 'Spain'],
  ['lk', 'Sri Lanka'],
  ['bl', 'St Barthélemy'],
  ['sh', 'St Helena'],
  ['kn', 'St Kitts and Nevis'],
  ['lc', 'St Lucia'],
  ['mf', 'St Martin'],
  ['pm', 'St Pierre and Miquelon'],
  ['vc', 'St Vincent and Grenadines'],
  ['sd', 'Sudan'],
  ['sr', 'Suriname'],
  ['sj', 'Svalbard and Jan Mayen'],
  ['se', 'Sweden'],
  ['ch', 'Switzerland'],
  ['sy', 'Syria'],
  ['tw', 'Taiwan'],
  ['tj', 'Tajikistan'],
  ['tz', 'Tanzania'],
  ['th', 'Thailand'],
  ['tl', 'Timor-Leste'],
  ['tg', 'Togo'],
  ['tk', 'Tokelau'],
  ['to', 'Tonga'],
  ['tt', 'Trinidad and Tobago'],
  ['tn', 'Tunisia'],
  ['tr', 'Türkiye'],
  ['tm', 'Turkmenistan'],
  ['tc', 'Turks and Caicos Islands'],
  ['tv', 'Tuvalu'],
  ['vi', 'US Virgin Islands'],
  ['ug', 'Uganda'],
  ['ua', 'Ukraine'],
  ['ae', 'United Arab Emirates'],
  ['gb', 'United Kingdom'],
  ['us', 'United States'],
  ['uy', 'Uruguay'],
  ['uz', 'Uzbekistan'],
  ['vu', 'Vanuatu'],
  ['va', 'Vatican City'],
  ['ve', 'Venezuela'],
  ['vn', 'Vietnam'],
  ['wf', 'Wallis and Futuna'],
  ['eh', 'Western Sahara'],
  ['ye', 'Yemen'],
  ['zm', 'Zambia'],
  ['zw', 'Zimbabwe'],
]

export const COUNTRIES: readonly Country[] = NAMES.map(([code, name]) => ({
  code,
  name,
  flag: flagFor(code),
})).sort((a, b) => a.name.localeCompare(b.name))

const NAME_TO_FLAG: Map<string, string> = new Map(
  COUNTRIES.map((c) => [c.name.toLowerCase(), c.flag]),
)

/** Look up a flag for a country name (case-insensitive). Returns '' if
 * the name doesn't match — keeps free-text rows rendering cleanly. */
export function flagForCountryName(name: string | null | undefined): string {
  if (!name) return ''
  return NAME_TO_FLAG.get(name.trim().toLowerCase()) ?? ''
}
