// Weekly AI + storage cost summary. CLAUDE.md §32.
//
// Mondays 09:00 UTC. Aggregates last 7 days of `DriftSample.costUsd` by task
// (1% sample × 100 ≈ true daily spend) and counts S3-bound objects as a
// proxy for storage cost. Renders markdown, persists to S3, posts to
// #crm-finops via the Slack `postAlert` boundary in the worker.

// We type the DB reader structurally so this module does not depend on a
// generated Prisma type. The real client matches; tests pass a fake.
export interface CostDbReader {
  driftSample: {
    findMany: (args: {
      where: { sampledAt: { gte: Date; lte: Date } }
      select: { task: true; costUsd: true; sampledAt: true }
      take: number
    }) => Promise<Array<{ task: string; costUsd: number; sampledAt: Date }>>
  }
  interaction: {
    count: (args: {
      where: { type: string; occurredAt: { gte: Date; lte: Date } }
    }) => Promise<number>
  }
}

export interface CostSampleRow {
  task: string
  costUsd: number
  sampledAt: Date
}

export interface StorageProxyCounts {
  /** Aircall recordings retained over the last 7 days (proxy). */
  aircallRecordings: number
  /** Email attachments retained over the last 7 days (proxy). */
  emailAttachments: number
}

export interface CostSummary {
  weekIso: string // YYYY-Www
  periodFrom: Date
  periodTo: Date
  /** Per-task USD spend extrapolated from the 1% drift sample. */
  aiByTaskUsd: Record<string, number>
  /** Total AI spend USD for the week. */
  aiTotalUsd: number
  /** Storage proxy counts. */
  storage: StorageProxyCounts
  /** True iff the report was newly generated, false on idempotent re-run. */
  freshlyGenerated: boolean
}

function isoWeek(d: Date): string {
  // Simple ISO week derivation. Monday-based, UTC.
  const tmp = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()))
  const dayNum = tmp.getUTCDay() || 7
  tmp.setUTCDate(tmp.getUTCDate() + 4 - dayNum)
  const yearStart = new Date(Date.UTC(tmp.getUTCFullYear(), 0, 1))
  const weekNo = Math.ceil(((tmp.getTime() - yearStart.getTime()) / 86_400_000 + 1) / 7)
  return `${tmp.getUTCFullYear()}-W${String(weekNo).padStart(2, '0')}`
}

/** Pure aggregator. Tested directly. */
export function aggregateCostSummary(input: {
  samples: ReadonlyArray<CostSampleRow>
  storage: StorageProxyCounts
  now: Date
  /** The 1% drift sample is multiplied by 100 to estimate true spend. */
  sampleMultiplier?: number
}): CostSummary {
  const multiplier = input.sampleMultiplier ?? 100
  const periodFrom = new Date(input.now.getTime() - 7 * 24 * 60 * 60 * 1000)
  const aiByTaskUsd: Record<string, number> = {}
  for (const s of input.samples) {
    if (s.sampledAt < periodFrom || s.sampledAt > input.now) continue
    aiByTaskUsd[s.task] = (aiByTaskUsd[s.task] ?? 0) + s.costUsd * multiplier
  }
  const aiTotalUsd = Object.values(aiByTaskUsd).reduce((a, b) => a + b, 0)
  return {
    weekIso: isoWeek(input.now),
    periodFrom,
    periodTo: input.now,
    aiByTaskUsd,
    aiTotalUsd,
    storage: input.storage,
    freshlyGenerated: true,
  }
}

/** Renders a deterministic markdown report. */
export function renderCostMarkdown(summary: CostSummary): string {
  const lines: string[] = []
  lines.push(`# StudyMind CRM cost summary — ${summary.weekIso}`)
  lines.push('')
  lines.push(
    `Period: ${summary.periodFrom.toISOString().slice(0, 10)} → ${summary.periodTo
      .toISOString()
      .slice(0, 10)}`,
  )
  lines.push('')
  lines.push('## AI spend (estimated from 1% drift sample × 100)')
  const tasks = Object.entries(summary.aiByTaskUsd).sort((a, b) => b[1] - a[1])
  if (tasks.length === 0) {
    lines.push('No samples recorded.')
  } else {
    lines.push('| Task | USD (est) |')
    lines.push('| --- | ---: |')
    for (const [task, usd] of tasks) {
      lines.push(`| \`${task}\` | $${usd.toFixed(2)} |`)
    }
    lines.push(`| **Total** | **$${summary.aiTotalUsd.toFixed(2)}** |`)
  }
  lines.push('')
  lines.push('## Storage (proxy counts)')
  lines.push(`- Aircall recordings retained: ${summary.storage.aircallRecordings}`)
  lines.push(`- Email attachments retained: ${summary.storage.emailAttachments}`)
  lines.push('')
  lines.push(
    '_Generated by `cost-summary` Inngest function. CLAUDE.md §32._',
  )
  return lines.join('\n')
}

export interface CollectCostInputsResult {
  samples: CostSampleRow[]
  storage: StorageProxyCounts
}

/**
 * Read the inputs needed for the weekly summary from the DB. Pure-ish: takes
 * a DB client and the `now`. Tests pass a fake DB.
 */
export async function collectCostInputs(
  db: CostDbReader,
  now: Date,
): Promise<CollectCostInputsResult> {
  const periodFrom = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

  const samplesRaw = await db.driftSample.findMany({
    where: { sampledAt: { gte: periodFrom, lte: now } },
    select: { task: true, costUsd: true, sampledAt: true },
    take: 50_000,
  })
  const samples: CostSampleRow[] = samplesRaw.map((s: { task: string; costUsd: number; sampledAt: Date }) => ({
    task: s.task,
    costUsd: s.costUsd,
    sampledAt: s.sampledAt,
  }))

  // Aircall recording proxy: count Interaction rows of type 'call' added in
  // the period. Email attachment proxy: count `email_received` interactions.
  const [callCount, emailCount] = await Promise.all([
    db.interaction.count({
      where: { type: 'call', occurredAt: { gte: periodFrom, lte: now } },
    }),
    db.interaction.count({
      where: {
        type: 'email_received',
        occurredAt: { gte: periodFrom, lte: now },
      },
    }),
  ])

  return {
    samples,
    storage: { aircallRecordings: callCount, emailAttachments: emailCount },
  }
}

export function costSummaryS3Key(weekIso: string): string {
  return `cost-reports/${weekIso}.md`
}

import { db } from '@studymind/db'

import { inngest } from './client'

export const costSummaryFunction = inngest.createFunction(
  {
    id: 'cost/weekly-summary',
    name: 'Cost: weekly AI + storage summary',
    concurrency: { limit: 1 },
    retries: 3,
  },
  // Mondays 09:00 UTC — CLAUDE.md §32.
  { cron: '0 9 * * 1' },
  async ({ step, logger }) => {
    const now = new Date()
    const inputs = (await step.run('collect', () =>
      collectCostInputs(db as unknown as CostDbReader, now),
    )) as unknown as CollectCostInputsResult
    const summary = aggregateCostSummary({
      samples: inputs.samples.map((s) => ({
        task: s.task,
        costUsd: s.costUsd,
        sampledAt: new Date(s.sampledAt),
      })),
      storage: inputs.storage,
      now,
    })
    const md = renderCostMarkdown(summary)
    const s3Key = costSummaryS3Key(summary.weekIso)
    logger.info(
      {
        weekIso: summary.weekIso,
        aiTotalUsd: summary.aiTotalUsd,
        s3Key,
      },
      'cost.summary.generated',
    )
    // S3 put + Slack post are wired at the worker boundary in
    // apps/web/app/api/inngest/route.ts to avoid jobs↔integration cycles.
    return { s3Key, weekIso: summary.weekIso, aiTotalUsd: summary.aiTotalUsd, markdown: md }
  },
)

export const COST_SUMMARY_FUNCTIONS = [costSummaryFunction]
