// Deterministic-looking, unique synthetic data for E2E specs.
// CLAUDE.md §23.1: no real PII in fixtures. Use the Ofcom-reserved
// +44 7700 900xxx test range for phone numbers and *.invalid for email.

import { randomUUID } from 'node:crypto'

function shortId(): string {
  return randomUUID().slice(0, 6)
}

export interface ContactInput {
  firstName: string
  lastName: string
  email: string
  phoneE164: string
  kind: 'parent' | 'student' | 'tutor' | 'la_caseworker' | 'other'
}

export function randomContactInput(overrides: Partial<ContactInput> = {}): ContactInput {
  const id = shortId()
  // Last three digits of +44 7700 900xxx are 0-999. Derive deterministically
  // from the uuid so two specs running in parallel still get unique numbers.
  const tail = parseInt(id, 16) % 1000
  const phoneTail = tail.toString().padStart(3, '0')
  return {
    firstName: `Test${id}`,
    lastName: `Family${id.toUpperCase()}`,
    email: `e2e-${id}@test.studymind.invalid`,
    phoneE164: `+447700900${phoneTail}`,
    kind: 'parent',
    ...overrides,
  }
}

export function randomNoteInput(): { summary: string; body: string } {
  const id = shortId()
  return {
    summary: `E2E note ${id}`,
    body: `This is a synthetic note generated by the E2E suite (${id}).`,
  }
}
